
language: cpp
sudo: false
dist: trusty

env:
  global:
    os: linux

jobs:
    include:
        - stage: build
          - compiler: g++
          - env: CMAKE_FLAGS = "-DCMAKE_BUILD_TYPE=Release"
          - compiler: clang
          - env: CMAKE_FLAGS = "-DCMAKE_BUILD_TYPE=Debug"
          - compiler: clang
          - env: CMAKE_FLAGS = "-DCMAKE_BUILD_TYPE=Release"
          - compiler: clang
          - env: CMAKE_FLAGS = "-DCMAKE_BUILD_TYPE=Debug"
        - stage: lint2
          - env: CI_TARGET=lint
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov

before_install:
#    - docker pull phuschke/githubcppprojecttemplate:v1
#    - docker run -itd --name build -v $(pwd):/project phuschke/githubcppprojecttemplate:v1
#   ALTERNATIVE: we could also clone the repo instead of mounting it with -v $(pwd):/project
#   - docker run -itd --name build phuschke/githubcppprojecttemplate:v1
#   - docker exec build git clone https://github.com/phuschke/GithubCppProjectTemplate.git /project

script: ci/script.sh

after_success:
  #  # Creating report
  #- cd ${TRAVIS_BUILD_DIR}
  #- lcov --directory . --capture --output-file coverage.info # capture coverage info
  #- lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  #- lcov --remove coverage.info 'test/catch.hpp' --output-file coverage.info # filter out system
  #- lcov --list coverage.info #debug info
  ## Uploading report to CodeCov
  #- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
