language: cpp
sudo: required
dist: trusty

os: linux

env:
  global:
    - CI_TARGET=test
    - BUILD_DIR="$TRAVIS_BUILD_DIR/build"

jobs:
  include:
    - stage: build
      compiler: g++
      env: CMAKE_FLAGS = "-DCMAKE_BUILD_TYPE=Release"
    - compiler: g++
      env: CMAKE_FLAGS = "-DCMAKE_BUILD_TYPE=Debug"
    - compiler: clang++
      env: CMAKE_FLAGS = "-DCMAKE_BUILD_TYPE=Release"
    - compiler: clang++
      env: CMAKE_FLAGS = "-DCMAKE_BUILD_TYPE=Debug"
    - stage: lint
      env: CI_TARGET=lint

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: lcov

script: sudo ci/script.sh
