language: cpp
sudo: false
dist: trusty

env:
  global:
    os: linux

jobs:
  include:
    - stage: build
      compiler: g++
      env: CMAKE_FLAGS = "-DCMAKE_BUILD_TYPE=Release"
    - compiler: clang
      env: CMAKE_FLAGS = "-DCMAKE_BUILD_TYPE=Debug"
    - compiler: clang
      env: CMAKE_FLAGS = "-DCMAKE_BUILD_TYPE=Release"
    - compiler: clang
      env: CMAKE_FLAGS = "-DCMAKE_BUILD_TYPE=Debug"
    - stage: lint2
      env: CI_TARGET=lint
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: lcov

before_install:


script: ci/script.sh

after_success:
