language: cpp
sudo: required

services:
    - docker
dist: trusty

compiler:
    - g++
env:
    - BUILD_TYPE=Debug
    
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov
            
before_install:
    - docker pull phuschke/githubcppprojecttemplate:v1
    - docker run -itd --name build -v $(pwd):/project phuschke/githubcppprojecttemplate:v1
#   ALTERNATIVE: we could also clone the repo instead of mounting it with -v $(pwd):/project
#   - docker run -itd --name build phuschke/githubcppprojecttemplate:v1
#   - docker exec build git clone https://github.com/phuschke/GithubCppProjectTemplate.git /project
script:
    - docker exec build cmake -H/project -B/build
    - docker exec build cmake --build /build
    - docker exec build cmake --build /build --target test
    - docker exec build lcov --directory /build --capture --output-file coverage.info
    - docker exec build lcov --remove coverage.info '/usr/*' --output-file coverage.info
    - docker exec build lcov --remove coverage.info 'test/catch.hpp' --output-file coverage.info
    - docker exec build bash <(curl -s https://codecov.io/bash)
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make -j2
    - ctest
after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --remove coverage.info 'test/catch.hpp' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
